/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as TodayRouteImport } from './routes/today'
import { Route as MilestonesRouteImport } from './routes/milestones'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as BodyRouteImport } from './routes/body'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutDateRouteImport } from './routes/workout.$date'

const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestonesRoute = MilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyRoute = BodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutDateRoute = WorkoutDateRouteImport.update({
  id: '/workout/$date',
  path: '/workout/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/body': typeof BodyRoute
  '/coach': typeof CoachRoute
  '/login': typeof LoginRoute
  '/milestones': typeof MilestonesRoute
  '/today': typeof TodayRoute
  '/trends': typeof TrendsRoute
  '/workout/$date': typeof WorkoutDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/body': typeof BodyRoute
  '/coach': typeof CoachRoute
  '/login': typeof LoginRoute
  '/milestones': typeof MilestonesRoute
  '/today': typeof TodayRoute
  '/trends': typeof TrendsRoute
  '/workout/$date': typeof WorkoutDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/body': typeof BodyRoute
  '/coach': typeof CoachRoute
  '/login': typeof LoginRoute
  '/milestones': typeof MilestonesRoute
  '/today': typeof TodayRoute
  '/trends': typeof TrendsRoute
  '/workout/$date': typeof WorkoutDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/body'
    | '/coach'
    | '/login'
    | '/milestones'
    | '/today'
    | '/trends'
    | '/workout/$date'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/body'
    | '/coach'
    | '/login'
    | '/milestones'
    | '/today'
    | '/trends'
    | '/workout/$date'
  id:
    | '__root__'
    | '/'
    | '/body'
    | '/coach'
    | '/login'
    | '/milestones'
    | '/today'
    | '/trends'
    | '/workout/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BodyRoute: typeof BodyRoute
  CoachRoute: typeof CoachRoute
  LoginRoute: typeof LoginRoute
  MilestonesRoute: typeof MilestonesRoute
  TodayRoute: typeof TodayRoute
  TrendsRoute: typeof TrendsRoute
  WorkoutDateRoute: typeof WorkoutDateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestones': {
      id: '/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof MilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body': {
      id: '/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof BodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$date': {
      id: '/workout/$date'
      path: '/workout/$date'
      fullPath: '/workout/$date'
      preLoaderRoute: typeof WorkoutDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BodyRoute: BodyRoute,
  CoachRoute: CoachRoute,
  LoginRoute: LoginRoute,
  MilestonesRoute: MilestonesRoute,
  TodayRoute: TodayRoute,
  TrendsRoute: TrendsRoute,
  WorkoutDateRoute: WorkoutDateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
